# Generated by Django 3.2.4 on 2022-09-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_appl_review_sys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
