# Generated by Django 3.2.4 on 2022-09-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_appl_review_sys', '0002_alter_candidate_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='id',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
