# Generated by Django 3.2.4 on 2022-09-06 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job_appl_review_sys', '0003_auto_20220906_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='edu',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='workexp',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
