# Generated by Django 3.2.4 on 2022-09-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_appl_review_sys', '0004_auto_20220906_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(default='Applied', max_length=100),
        ),
    ]
