# Generated by Django 3.2.4 on 2022-09-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_appl_review_sys', '0006_alter_candidate_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='edu',
            new_name='edu_level',
        ),
        migrations.AddField(
            model_name='candidate',
            name='result',
            field=models.FloatField(default=0),
        ),
    ]
