# Generated by Django 3.2.4 on 2022-09-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_appl_review_sys', '0008_candidate_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='filename',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
